name: build-deploy

on:
  push:
    branches: [ main ]

jobs:
  build-dev:
    name: Build-Dev
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short $GITHUB_SHA)"

    - name: 'Save Sha'
      run: echo "$GITHUB_SHA" >> deploy/GITHUB_SHA

    - name: 'Save Branch'
      run: echo "$GITHUB_REF" >> deploy/BRANCH_NAME

    - name: 'Save Short Sha'
      env:
        DEPLOYMENT_GITSHORTSHA: ${{ steps.vars.outputs.sha_short }}
      run: echo "$DEPLOYMENT_GITSHORTSHA" >> deploy/GITHUB_SHORT_SHA

    - name: 'Upload Js'
      uses: actions/upload-artifact@v2
      with:
        name: js
        path: .
        retention-days: 5

    - name: Set Config
      env: 
        PROJECT_SERVER_HOST: ${{ secrets.DEV_PROJECT_SERVER_HOST }}
        NAMESPACE: ${{ secrets.DEV_NAMESPACE }}
        APP_PUBLIC_PATH: ${{ secrets.DEV_APP_PUBLIC_PATH }}
      run: |
         envsubst < src/config/projectConfig.js > tempConfig
         cat tempConfig > src/config/projectConfig.js
         envsubst < vite.config.js.template > tempViteConfig
         cat tempViteConfig > vite.config.js
         envsubst '$APP_PUBLIC_PATH' < nginx.conf > tempNginxConf
         cat tempNginxConf > nginx.conf
         rm tempViteConfig tempConfig tempNginxConf
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        context: .
        file: ./Dockerfile
        push: true 
        tags: horvatic/zracni-udar-ui:dev${{ steps.vars.outputs.sha_short }}
        build-args: |
          PUBLIC_PATH=${{ secrets.DEV_NGINX_PUBLIC_PATH }}

  dev:
    name: Deploy-Dev
    environment:
      name: dev
    runs-on: ubuntu-latest
    needs: build-dev
    
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: js

    - name: 'Set Sha and Branch Name'
      id: vars
      run: |
        echo "::set-output name=deploy_git_sha::$(cat deploy/GITHUB_SHA)"
        echo "::set-output name=deploy_git_short_sha::$(cat deploy/GITHUB_SHORT_SHA)"
        echo "::set-output name=deploy_branch_name::$(cat deploy/BRANCH_NAME)"

    - name: Deploy
      env: 
        DEPLOYMENT_MONGO_CONNECTION_STRING: ${{ secrets.DEPLOYMENT_MONGO_CONNECTION_STRING }}
        DEPLOYMENT_MONGO_DATABASE: ${{ secrets.DEPLOYMENT_MONGO_DATABASE }}
        DEPLOYMENT_MONGO_COLLECTION: ${{ secrets.DEPLOYMENT_MONGO_COLLECTION }}
        DEPLOYMENT_ENV: "dev"
        DEPLOYMENT_GITSHA: ${{ steps.vars.outputs.deploy_git_sha }}
        DEPLOYMENT_GIT_SHORT_SHA: ${{ steps.vars.outputs.deploy_git_short_sha }}
        DEPLOYMENT_BRANCH_NAME: ${{ steps.vars.outputs.deploy_branch_name }}
      run: |
        cd deploy/scripts/update 
        go mod tidy
        go run main.go

  build-prod:
    name: Build-Prod
    runs-on: ubuntu-latest
    needs: dev

    steps:

    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: js

    - name: 'Set Short Sha'
      id: vars
      run: |
        echo "::set-output name=sha_short::$(cat deploy/GITHUB_SHORT_SHA)"

    - name: Set Config
      env:
        PROJECT_SERVER_HOST: ${{ secrets.PROD_PROJECT_SERVER_HOST }}
        NAMESPACE: ${{ secrets.PROD_NAMESPACE }}
        APP_PUBLIC_PATH: ${{ secrets.PROD_APP_PUBLIC_PATH }}
      run: |
         envsubst < src/config/projectConfig.js > tempConfig
         cat tempConfig > src/config/projectConfig.js
         envsubst < vite.config.js.template > tempViteConfig
         cat tempViteConfig > vite.config.js
         envsubst '$APP_PUBLIC_PATH' < nginx.conf > tempNginxConf
         cat tempNginxConf > nginx.conf
         rm tempViteConfig tempConfig tempNginxConf

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64
        context: .
        file: ./Dockerfile
        push: true
        tags: horvatic/zracni-udar-ui:prod${{ steps.vars.outputs.sha_short }}
        build-args: |
          PUBLIC_PATH=${{ secrets.PROD_NGINX_PUBLIC_PATH }}

  prod:
    name: Deploy-Prod
    environment:
      name: prod
    runs-on: ubuntu-latest
    needs: build-prod

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Download Deploy
      uses: actions/download-artifact@v2
      with:
        name: js

    - name: 'Set Sha and Branch Name'
      id: vars
      run: |
        echo "::set-output name=deploy_git_sha::$(cat deploy/GITHUB_SHA)"
        echo "::set-output name=deploy_git_short_sha::$(cat deploy/GITHUB_SHORT_SHA)"
        echo "::set-output name=deploy_branch_name::$(cat deploy/BRANCH_NAME)"

    - name: Deploy
      env:
        DEPLOYMENT_MONGO_CONNECTION_STRING: ${{ secrets.DEPLOYMENT_MONGO_CONNECTION_STRING }}
        DEPLOYMENT_MONGO_DATABASE: ${{ secrets.DEPLOYMENT_MONGO_DATABASE }}
        DEPLOYMENT_MONGO_COLLECTION: ${{ secrets.DEPLOYMENT_MONGO_COLLECTION }}
        DEPLOYMENT_ENV: "prod"
        DEPLOYMENT_GITSHA: ${{ steps.vars.outputs.deploy_git_sha }}
        DEPLOYMENT_GIT_SHORT_SHA: ${{ steps.vars.outputs.deploy_git_short_sha }}
        DEPLOYMENT_BRANCH_NAME: ${{ steps.vars.outputs.deploy_branch_name }}
      run: |
        cd deploy/scripts/update
        go mod tidy
        go run main.go
